/*
 * action types
 */
export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const ADD_TEXT = "ADD_TEXT";
export const DELETE_TEXT = "DELETE_TEXT";
export const SIMPLE_ACTION = "SIMPLE_ACTION";
export const GET_TRELLO_MEMBERS_REQUEST = "GET_TRELLO_MEMBERS_REQUEST";
export const GET_TRELLO_MEMBERS_FAILURE = "GET_TRELLO_MEMBERS_FAILURE";
export const GET_TRELLO_MEMBERS_SUCCESS = "GET_TRELLO_MEMBERS_SUCCESS";
export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";
export const LOAD_BLOG_SUCCESS = "LOAD_BLOG_SUCCESS";
export const DELETE_ITEM = "DELETE_ITEM";
